-- Custom programmes generated by the quiz belong to a single player.
ALTER TABLE "Programme"
    ADD COLUMN "isCustom"           BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN "createdForPlayerId" UUID;

ALTER TABLE "Programme"
    ADD CONSTRAINT "Programme_createdForPlayerId_fkey"
    FOREIGN KEY ("createdForPlayerId") REFERENCES "Player"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX "Programme_createdForPlayerId_idx"
    ON "Programme" ("createdForPlayerId");
